# mkinitcpio configuration for Surface Pro 11 (Snapdragon X Plus)

MODULES=(
    # Storage
    nvme usb_storage uas xhci_hcd sdhci sdhci_msm
    # GPU / Display
    msm simpledrm
    # Filesystems
    ext4 vfat
)

BINARIES=()

FILES=(
    /etc/modprobe.d/x1p-gpu.conf
)

HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)

# Compression
COMPRESSION="zstd"

# Modules to load early
MODULES_DECOMPRESS="yes"
