title   Arch Linux ARM - Console (text login, simpledrm)
linux   /Image
initrd  /initramfs.img
devicetree /dtbs/qcom/x1e80100-microsoft-romulus13.dtb
options root=LABEL=ARCH_X1P_ROOT rw rootfstype=ext4 console=tty0 loglevel=7 ignore_loglevel consoleblank=0 rd.udev.log_level=info clk_ignore_unused pd_ignore_unused panic=20 modprobe.blacklist=msm,kgsl,ath12k,dispcc_x1e80100,gpucc_x1e80100 systemd.unit=multi-user.target
